name: idioms_and_phrases
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  firebase_core: ^3.1.0
  firebase_auth: ^5.1.0
  flutter:
    sdk: flutter

  carousel_slider: ^4.2.1
  http: ^1.2.1

  flutter_onboarding_slider: ^1.0.11
  shared_preferences: ^2.2.3
  flutter_tts: ^4.0.2

  lottie: ^2.1.0
  url_launcher: ^6.3.0
  flutter_bloc: ^8.1.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  assets:
  - assets/


  
